spring:
  main:
    allow-bean-definition-overriding: true
  security:
    filter:
      order: 0

db_server:
  host: "localhost"
  port: "5438"
  database: "financial_api"
  username: "root"
  password: "root"

jwt_secret: MjE5dzhzZDlhZDg5c2FkOGE5c2Q4czlhZDhhczllODUyMTk4cnEzOTQ4OXc4OXc4ZWQ5ZDhhOWQ4YTk0ODI5KnI4dGc5ZHQ4NTk=
jwt_expiration: 120
