name: Publish Docker image

on:
  release:
    types: [published]
jobs:
  build_and_push_dockerhub:
    name: Build do projeto e envio para o dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Efetuar checkout do repositorio
        uses: actions/checkout@v3

      - name: Efetua login no dockerhub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extrai dados do dockerhub sobre versoes
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: rafaelmarquespaixao/financial-api

      - name: iniciar ambiente java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: build gradle
        run: ./gradlew build

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_ec2:
    needs: build_and_push_dockerhub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.AWS_HOSTNAME  }}
          USER_NAME: ${{ secrets.AWS_USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu &&
            sh deploy_frontend.sh ${{secrets.DOCKERHUB_LOGIN}} ${{secrets.DOCKERHUB_PASSWORD}} financial-api backend
          '
